# Generated by Django 3.1.2 on 2020-10-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finance_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Joined', models.DateField()),
                ('Paid_Till', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Roll_Number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('BirthDate', models.DateField(blank=True, null=True)),
                ('Class', models.CharField(choices=[('First', '1'), ('Second', '2'), ('Third', '3'), ('Fourth', '4'), ('Fifth', '5'), ('Sixth', '6'), ('seventh', '7'), ('eigth', '8'), ('Ninth', '9'), ('Tenth', '10')], default='First', max_length=10)),
                ('Parents_Contact_Number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Fee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='main.finance_db')),
            ],
            options={
                'ordering': ['Class'],
            },
        ),
        migrations.CreateModel(
            name='Faculty_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Subject', models.CharField(max_length=30)),
                ('Contact', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Payment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='main.finance_db')),
            ],
        ),
    ]
