# Generated by Django 3.1.2 on 2020-10-22 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Role', models.CharField(max_length=30)),
                ('Contact_Number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Payment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='main.finance_db')),
            ],
        ),
    ]
