# Generated by Django 3.1.2 on 2020-10-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_faculty_db_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('BirthDate', models.DateField(blank=True, null=True)),
                ('Class', models.CharField(choices=[('First', '1'), ('Second', '2'), ('Third', '3'), ('Fourth', '4'), ('Fifth', '5'), ('Sixth', '6'), ('seventh', '7'), ('eigth', '8'), ('Ninth', '9'), ('Tenth', '10')], default='First', max_length=10)),
                ('Parents_Contact_Number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
