# Generated by Django 3.1.2 on 2020-10-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_student_db'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_db',
            options={'ordering': ['Class']},
        ),
    ]
